<h1 style="text-align:center; color:red">NUMPY<h1>

<h2 style="color:blue">NumPy is a Python library for numerical computing, offering support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.</h3>

In [308]:
pip install numpy  ##installing numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '##installing'


In [309]:
import numpy as np

In [310]:
ls=[12,34,35,23]

In [311]:
a=np.array(ls)
print(a)
print(type(a))

[12 34 35 23]
<class 'numpy.ndarray'>


In [312]:
for i in a:
    print(i)

12
34
35
23


In [313]:
a=a+5 ## added to all elements
print(a)

[17 39 40 28]


In [314]:
a.ndim ## returns dimension

1

In [315]:
#[[],[],[]...] ## structure of 2-d array

In [316]:
l=[22,"ds"]

In [317]:
ar=np.array(l) ##converting list to array

In [318]:
print(ar)

['22' 'ds']


In [319]:
print(type(ar[0])) ##returns type of element of the array

<class 'numpy.str_'>


In [320]:
ar.dtype ##returns data type of elemn=ents of array

dtype('<U11')

In [321]:
a.dtype

dtype('int32')

In [322]:
print(a[2])
print(a)
print(id(ar)) ##accessing location of element in array

40
[17 39 40 28]
2054882781072


In [323]:
lst=[22,45,23,46,23,8,23,79,27]
arr=np.array(lst)
arr

array([22, 45, 23, 46, 23,  8, 23, 79, 27])

In [324]:
print(arr[0:4:2])

[22 23]


In [325]:
print(arr.size)
print(len(arr))

9
9


In [326]:
for i in arr:
    if i<50:
        print(i)

22
45
23
46
23
8
23
27


In [327]:
arr[arr<50] ##returns an array with elements less than 50

array([22, 45, 23, 46, 23,  8, 23, 27])

In [328]:
arr.shape ##returns number of elements and dimensions

(9,)

In [329]:
np.arange(1,50,2) ## it returns an array from 1 to 49 with step 2 with one dimension.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [330]:
print(np.ones(10)) ## returns 10 times ones(1's)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [331]:
np.ones((10,5)) ##returns 2-d array with 10 rows and 5 columns of ones(1's)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [332]:
lse=[[1,2],[3,4],[5,6]] ##initialization of 2-d array
x=np.array(lse)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [333]:
np.zeros((10,5,6)) ## returns 3-d array (combionation of more than 1 two dimensional array)

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
    

In [334]:
np.linspace(1,8,5) ## returns 5 items between 1 to 8.

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [335]:
import random ## Random library
print(random.randint(1,5)) ## returns random integer number between 1 to 5 but excluding 5.
print(random.random()) ## returns random floating point number from 0 to 1.
print(random.randrange(1,4)) ## returns random integer from 1 to 4 excluding 4.


5
0.647843897080713
1


In [336]:
lsw=["kartik","ronak","priyanshi"]
print(random.choice(lsw)) ## returns random element from the list.
print(random.choices(lsw,k=2)) ## returns random 2 elements from list.


priyanshi
['kartik', 'priyanshi']


In [337]:
random.shuffle(lsw) ## shuffle items in the list.
print(lsw)

['ronak', 'kartik', 'priyanshi']


In [338]:
print(np.random.randint(1,50,10)) ## returns 1-d array from 1 to 50 (10 elements)

[ 4 11 10 20 30 43 18 25  1 10]


In [339]:
print(np.random.randint(1,50,(10,5))) ## returns 2-d array from 1 to 50 (10 rows and 5 columns)

[[20  5  7 43 19]
 [ 8  5 39 36 39]
 [24 24 13  5 40]
 [26  4 35 11 49]
 [41  9 18  3 14]
 [16 31 13 10  7]
 [41 15 36 34  4]
 [43 40 21 13 18]
 [12 13 46 28 38]
 [41 37 13 20 14]]


In [340]:
ae=np.arange(108)
ae

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107])

In [341]:
ae.reshape(12,9) ## change shape (dimension) of array.

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107]])

In [342]:
ae

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107])

In [343]:
ae.resize(9,12) # change dimension of array
print(ae)

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]]


In [344]:
ae.sum() ## returns sum of elements of array.

5778

In [345]:
ae.shape ## returns rows and columns of array (shape)

(9, 12)

In [346]:
ae.ndim ## returns dimension of array.

2

In [347]:
ae.reshape(108) ## change dimension (shape)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107])

In [348]:
ae.ravel() ## convert nd to 1-d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107])

In [349]:
ae.flatten() ## same as ravel

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107])

In [350]:
arr=np.random.randint(5,50,100) ## returns array of random elements with 100 items from 5 to 50.
print(arr)

[42 10 16 37 21 26 11 33 19 26 34 33 34 14 48 11 38 17 11 19 42 18  9 37
 35 24 38 31 21 31 34 23 39 47 41  7 31  7 33 20 19 36 39 16 14 45 27 18
  6 43 34 31  8 24 25  5 45 25 49 28 11 30 16 39 21 47 49 13 35 27 35 27
 45 11 10 11  7 33 38 20 15  9 27  7 36 26  5 13 15 13 10 14 48 14 30 17
 30 24 35 43]


In [351]:
print(arr.sum()) ## returns sum of elements of array (arr).

2561


In [352]:
print(arr.mean()) #n returns mean(average) of elements of array.

25.61


In [353]:
arr2=np.random.randint(5,50,(4,3)) ## returns 2-d array of random elements with 4 rows and 3 columns from 5 to 50.
print(arr2)

[[29 37 25]
 [16  9 27]
 [40 38  7]
 [13 43 30]]


In [354]:
arr2.shape

(4, 3)

In [355]:
print(np.transpose(arr2)) ## transpose 2-d array (change rows with column and vice-versa.)

[[29 16 40 13]
 [37  9 38 43]
 [25 27  7 30]]


In [356]:
print(arr2.T) ## same as transpose

[[29 16 40 13]
 [37  9 38 43]
 [25 27  7 30]]


In [357]:
arr3=np.random.randint(2,12,(10,5))
print(arr3)

[[ 6 11 10  7  7]
 [ 6 11  6  3  9]
 [ 7 11  3 11  2]
 [ 9  5  7  5  7]
 [ 5  5  2  8  4]
 [ 4  7 10  4  3]
 [ 6  8 10  8 11]
 [ 9 11  3  4  3]
 [10  7  9  8  7]
 [ 6  8 10 10  6]]


In [358]:
arr3.reshape(50) ##converts arr3 to 1-d

array([ 6, 11, 10,  7,  7,  6, 11,  6,  3,  9,  7, 11,  3, 11,  2,  9,  5,
        7,  5,  7,  5,  5,  2,  8,  4,  4,  7, 10,  4,  3,  6,  8, 10,  8,
       11,  9, 11,  3,  4,  3, 10,  7,  9,  8,  7,  6,  8, 10, 10,  6])

In [359]:
np.ravel(arr3) ## converts arr3 to 1-d

array([ 6, 11, 10,  7,  7,  6, 11,  6,  3,  9,  7, 11,  3, 11,  2,  9,  5,
        7,  5,  7,  5,  5,  2,  8,  4,  4,  7, 10,  4,  3,  6,  8, 10,  8,
       11,  9, 11,  3,  4,  3, 10,  7,  9,  8,  7,  6,  8, 10, 10,  6])

In [360]:
arr3.flatten() ## same as ravel

array([ 6, 11, 10,  7,  7,  6, 11,  6,  3,  9,  7, 11,  3, 11,  2,  9,  5,
        7,  5,  7,  5,  5,  2,  8,  4,  4,  7, 10,  4,  3,  6,  8, 10,  8,
       11,  9, 11,  3,  4,  3, 10,  7,  9,  8,  7,  6,  8, 10, 10,  6])

In [361]:
print(arr3[3:6,2:]) ## accessing elements from array.

[[ 7  5  7]
 [ 2  8  4]
 [10  4  3]]


In [362]:
arr3[::2,2:]

array([[10,  7,  7],
       [ 3, 11,  2],
       [ 2,  8,  4],
       [10,  8, 11],
       [ 9,  8,  7]])

3-D

In [363]:

arr=np.random.randint(2,12,(5,10,5)) ## returns 3-d array with 5 layers, 10 rows and 5 columns from 2 to 12
print(arr)

[[[ 8  2  6  3  9]
  [ 5  9  2  3  5]
  [ 3  8  3 11  5]
  [ 9 10 10  2 11]
  [ 8  6  8  3 11]
  [10  2  5 11  5]
  [ 9  2 10  3 10]
  [11 10  5 10  6]
  [ 6  2  9  6  9]
  [ 3  2  8  8  5]]

 [[10  5  5  7 11]
  [10  4  4  2 11]
  [10  5  6 11  9]
  [ 4  2  9  4  7]
  [ 4  7  9  6  4]
  [ 3 10 11 10  3]
  [ 5 10  5 11  8]
  [ 2  5 11 10  7]
  [11  5  6  4 10]
  [ 6  2 10  6  4]]

 [[ 8 11  5  3  2]
  [ 9  5  2  2  5]
  [ 4  7  9  5  9]
  [11  4  6  9 10]
  [11  6  9  3  5]
  [ 8  6  6  4  4]
  [ 9  6  7  3  6]
  [10  4 10 11 11]
  [ 6  8  3  7  4]
  [ 8  3  5  9 11]]

 [[ 4  3  3  5 10]
  [ 5 11  8  2  8]
  [ 7  2  8  3  3]
  [ 8 11  3  2  5]
  [ 2  2  5  6  7]
  [ 5  6  3  8  2]
  [11  9  6  8 11]
  [ 9  5  4  8 11]
  [ 8  3  2  9  3]
  [ 9  4  5  8  5]]

 [[10  8  2  7  8]
  [ 9  5  8  6  5]
  [ 8  9  2  3  8]
  [ 5  2  3  2  3]
  [ 9  8  8 11  7]
  [ 6  8  3  7  5]
  [ 2  8  7  2  8]
  [ 8  2  6 10  4]
  [ 6  3  7  6  9]
  [ 6  8  7  7  3]]]


In [364]:
#3D==Tables,Rows,columns

In [365]:
arr[0] ## table [0]

array([[ 8,  2,  6,  3,  9],
       [ 5,  9,  2,  3,  5],
       [ 3,  8,  3, 11,  5],
       [ 9, 10, 10,  2, 11],
       [ 8,  6,  8,  3, 11],
       [10,  2,  5, 11,  5],
       [ 9,  2, 10,  3, 10],
       [11, 10,  5, 10,  6],
       [ 6,  2,  9,  6,  9],
       [ 3,  2,  8,  8,  5]])

In [366]:
arr[0][0] ## First row first table

array([8, 2, 6, 3, 9])

In [367]:
arr[0][0][0] ## accessing first element of first row of first table

8

In [368]:
print(arr[0:1,8:,2:]) ## accessing element from array

[[[9 6 9]
  [8 8 5]]]


In [369]:
print(arr[:,-1:,:])

[[[ 3  2  8  8  5]]

 [[ 6  2 10  6  4]]

 [[ 8  3  5  9 11]]

 [[ 9  4  5  8  5]]

 [[ 6  8  7  7  3]]]


In [370]:
arr.max() ## returns maximum value from array

11

In [371]:
arr.argmax() ## return index of maximum value from array

13

In [372]:
arr.sort() ## sort elements in array(only in 1 dimension. if applied on 2-d then sort elements in row only)
print(arr)

[[[ 2  3  6  8  9]
  [ 2  3  5  5  9]
  [ 3  3  5  8 11]
  [ 2  9 10 10 11]
  [ 3  6  8  8 11]
  [ 2  5  5 10 11]
  [ 2  3  9 10 10]
  [ 5  6 10 10 11]
  [ 2  6  6  9  9]
  [ 2  3  5  8  8]]

 [[ 5  5  7 10 11]
  [ 2  4  4 10 11]
  [ 5  6  9 10 11]
  [ 2  4  4  7  9]
  [ 4  4  6  7  9]
  [ 3  3 10 10 11]
  [ 5  5  8 10 11]
  [ 2  5  7 10 11]
  [ 4  5  6 10 11]
  [ 2  4  6  6 10]]

 [[ 2  3  5  8 11]
  [ 2  2  5  5  9]
  [ 4  5  7  9  9]
  [ 4  6  9 10 11]
  [ 3  5  6  9 11]
  [ 4  4  6  6  8]
  [ 3  6  6  7  9]
  [ 4 10 10 11 11]
  [ 3  4  6  7  8]
  [ 3  5  8  9 11]]

 [[ 3  3  4  5 10]
  [ 2  5  8  8 11]
  [ 2  3  3  7  8]
  [ 2  3  5  8 11]
  [ 2  2  5  6  7]
  [ 2  3  5  6  8]
  [ 6  8  9 11 11]
  [ 4  5  8  9 11]
  [ 2  3  3  8  9]
  [ 4  5  5  8  9]]

 [[ 2  7  8  8 10]
  [ 5  5  6  8  9]
  [ 2  3  8  8  9]
  [ 2  2  3  3  5]
  [ 7  8  8  9 11]
  [ 3  5  6  7  8]
  [ 2  2  7  8  8]
  [ 2  4  6  8 10]
  [ 3  6  6  7  9]
  [ 3  6  7  7  8]]]


In [373]:
ar=np.random.randint(5,10,3)
print(ar)

[6 5 7]


In [374]:
ar.sort()
print(ar)

[5 6 7]


In [375]:
ar.argsort() ## returns position of elements according to increasing order

array([0, 1, 2], dtype=int64)

In [376]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 9,  9, 10,  2,  3],
       [10, 11, 10,  2,  6],
       [10,  2, 11,  7,  3],
       [ 6,  4,  6,  7,  9],
       [10,  8,  5, 10,  9],
       [ 5,  2, 11, 10,  6],
       [ 4,  5,  3, 10,  8],
       [ 2,  3,  5,  3,  9],
       [ 3,  7,  5,  2,  6],
       [ 4,  6,  7,  9,  5]])

In [377]:
np.unique(arr) ## returns unique items (1 item, single time only)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [378]:
print(arr.mean()) ##returns mean of elements of array.
print(np.median(arr)) ## returns median of elements of array

6.38
6.0


In [379]:
print(arr.std()) ## returns standard daviation
print("\n\n")
print(np.sqrt(arr)) ## returns square root of elemnts of array.

2.9318253699700465



[[3.         3.         3.16227766 1.41421356 1.73205081]
 [3.16227766 3.31662479 3.16227766 1.41421356 2.44948974]
 [3.16227766 1.41421356 3.31662479 2.64575131 1.73205081]
 [2.44948974 2.         2.44948974 2.64575131 3.        ]
 [3.16227766 2.82842712 2.23606798 3.16227766 3.        ]
 [2.23606798 1.41421356 3.31662479 3.16227766 2.44948974]
 [2.         2.23606798 1.73205081 3.16227766 2.82842712]
 [1.41421356 1.73205081 2.23606798 1.73205081 3.        ]
 [1.73205081 2.64575131 2.23606798 1.41421356 2.44948974]
 [2.         2.44948974 2.64575131 3.         2.23606798]]


<h2 style='text-align:center; color:green'>Thank You</h2>